### ISSUE TITLE
Crowdfunding: Populate Name field for logged in users

### ISSUE THREAD

**Issue by rnestler** [coredump-ch/interna#28]
When I'm logged in I want the "Name" field to be filled in with my username or the Name I used last time.

**Comment by dbrgn** [comment]
What a privacy leak :scream:

Shouldn't be hard to implement. At [this line](https://github.com/coredump-ch/interna/blob/master/interna/crowdfund/views.py#L43), instead of returning the response, store it in a variable. Then add a cookie to the response: https://docs.djangoproject.com/en/dev/ref/request-response/#django.http.HttpResponse.set_cookie The key can be something like "last_pledge_name", the value is `form.cleaned_data.get('name')`.

Then in the [details page](https://github.com/coredump-ch/interna/blob/master/interna/crowdfund/templates/crowdfund/detail.html) inject a JavaScript snippet that extracts the cookie value and sets the value of the input field. The cleanest way to do that would be to extend the `scripts` block originalla defined [here](https://github.com/coredump-ch/interna/blob/master/interna/front/templates/front/base.html#L74-L79):

```django
{% block scripts %}
    {{ block.super }}
    <script ...
{% endblock scripts %}
```

@rnestler I heard you volunteered to implement this? :smile:

**Comment by rnestler** [comment]
> @rnestler I heard you volunteered to implement this? smile

On it :)
